// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yichwnykvacuzjnyhtjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpY2h3bnlrdmFjdXpqbnlodGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MzA1NjIsImV4cCI6MjA1MTMwNjU2Mn0.RLx5DkveBzvwYeGhwUrufjQh5cEGpDRC5jMqdYU4MLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);